#!/usr/bin/env python3
"""
Format consolidated pipeline logs into human-readable markdown.
"""

import argparse
import json
import sys
from pathlib import Path
from datetime import datetime


def parse_iso_datetime(iso_str: str) -> datetime:
    """Parse ISO format datetime string."""
    try:
        return datetime.fromisoformat(iso_str.replace("Z", "+00:00"))
    except:
        return datetime.utcnow()


def format_duration(start_iso: str, end_iso: str) -> str:
    """Calculate duration between two ISO timestamps."""
    try:
        start = parse_iso_datetime(start_iso)
        end = parse_iso_datetime(end_iso)
        delta = end - start
        
        hours = int(delta.total_seconds() // 3600)
        minutes = int((delta.total_seconds() % 3600) // 60)
        seconds = int(delta.total_seconds() % 60)
        
        if hours > 0:
            return f"{hours}h {minutes}m {seconds}s"
        elif minutes > 0:
            return f"{minutes}m {seconds}s"
        else:
            return f"{seconds}s"
    except:
        return "unknown"


def get_status_icon(status: str) -> str:
    """Get emoji icon for status."""
    if "error" in status.lower():
        return "❌"
    elif "warning" in status.lower():
        return "⚠️"
    else:
        return "✅"


def format_markdown(consolidated_log: dict) -> str:
    """Format consolidated log as markdown."""
    
    pxd = consolidated_log.get("pxd", "UNKNOWN")
    status = consolidated_log.get("status", "unknown")
    events = consolidated_log.get("events", [])
    summary = consolidated_log.get("summary", {})
    findings = consolidated_log.get("key_findings", {})
    missing = consolidated_log.get("missing_outputs", {})
    
    timestamp_start = consolidated_log.get("timestamp_start", "")
    timestamp_end = consolidated_log.get("timestamp_end", "")
    duration = format_duration(timestamp_start, timestamp_end)
    
    md = []
    
    # Header
    md.append(f"# {pxd} Pipeline Execution Summary\n")
    md.append(f"**Status:** {get_status_icon(status)} {status}")
    md.append(f"**Duration:** {duration}")
    md.append(f"**Execution Time:** {timestamp_start} to {timestamp_end}")
    md.append("")
    
    # Summary box
    md.append("## 📊 Execution Summary\n")
    md.append(f"- **Total Events:** {summary.get('total_events', 0)}")
    md.append(f"- **Errors:** {summary.get('errors', 0)}")
    md.append(f"- **Warnings:** {summary.get('warnings', 0)}")
    md.append(f"- **Processes:** {len(summary.get('processes', []))}")
    md.append(f"- **Version:** {consolidated_log.get('pipeline_version', 'unknown')}")
    md.append("")
    
    # Key findings
    if findings:
        md.append("## 🔍 Key Findings\n")
        
        # Quality issues
        if findings.get("quality_issues"):
            md.append("### Data Quality Issues")
            for issue in findings["quality_issues"][:3]:  # Limit to 3
                md.append(f"- **{issue.get('process')}:** {issue.get('message')}")
                if issue.get("details"):
                    md.append(f"  - Details: {issue['details']}")
            md.append("")
        
        # Decisions
        if findings.get("decisions"):
            md.append("### Process Decisions\n")
            for decision in findings["decisions"]:
                md.append(f"- **{decision.get('process')}:** {decision.get('decision')}")
                if decision.get("details"):
                    md.append(f"  - {json.dumps(decision['details'], indent=4)}")
            md.append("")
        
        # Skipped processes
        if findings.get("skipped_processes"):
            md.append("### Skipped Processes\n")
            for skip in findings["skipped_processes"]:
                md.append(f"- **{skip.get('process')}:** {skip.get('reason')}")
            md.append("")
    
    # Missing outputs
    if missing:
        md.append("## 📦 Missing Outputs\n")
        for output, reason in missing.items():
            md.append(f"- ❌ **{output}:** {reason}")
        md.append("")
    
    # Event timeline (last 20 events)
    if events:
        md.append("## ⏱️ Event Timeline\n")
        md.append("| Timestamp | Process | Level | Category | Message |")
        md.append("|-----------|---------|-------|----------|---------|")
        
        for event in events[-20:]:  # Show last 20 events
            ts = event.get("timestamp", "")[:19]  # Truncate to date+time
            process = event.get("process", "")[:15]
            level = event.get("level", "")
            category = event.get("category", "")
            message = event.get("message", "")[:50]
            
            md.append(f"| {ts} | {process} | {level} | {category} | {message} |")
        md.append("")
    
    # Footer
    md.append("---\n")
    md.append("*Generated by HAMLET annotator Pipeline Logger*")
    
    return "\n".join(md)


def main():
    parser = argparse.ArgumentParser(description="Format pipeline logs as markdown")
    parser.add_argument('--log_file', required=True, help='Consolidated log JSON file')
    parser.add_argument('--output_file', default=None, help='Output markdown file')
    
    args = parser.parse_args()
    
    if not args.output_file:
        log_path = Path(args.log_file)
        args.output_file = str(log_path.parent / log_path.stem) + "_summary.md"
    
    # Read consolidated log
    try:
        with open(args.log_file, 'r') as f:
            consolidated = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError) as e:
        print(f"ERROR: Could not read log file {args.log_file}: {e}", file=sys.stderr)
        return 1
    
    # Format as markdown
    markdown = format_markdown(consolidated)
    
    # Write output
    output_path = Path(args.output_file)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(output_path, 'w') as f:
        f.write(markdown)
    
    print(f"Markdown summary written to: {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
